import {
  Injectable,
  NotFoundException,
  BadRequestException,
  Logger,
} from '@nestjs/common';
import { Prisma } from '@insaat-erp/database';
import { PrismaService } from '../prisma/prisma.service';
import {
  CreateChequeDto,
  UpdateChequeStatusDto,
  ListChequesDto,
} from './dto/create-cheque.dto';

@Injectable()
export class ChequesService {
  private readonly logger = new Logger(ChequesService.name);

  constructor(private readonly prisma: PrismaService) {}

  // ════════════════════════════════════
  // CREATE (manuel)
  // ════════════════════════════════════
  async create(tenantId: string, userId: string, dto: CreateChequeDto) {
    const contact = await this.prisma.contact.findFirst({
      where: { id: dto.contactId, tenantId, deletedAt: null },
    });
    if (!contact) {
      throw new BadRequestException(`Cari bulunamadı: ${dto.contactId}`);
    }

    const cheque = await this.prisma.cheque.create({
      data: {
        tenantId,
        contactId: dto.contactId,
        kind: dto.kind,
        direction: dto.direction,
        chequeNo: dto.chequeNo,
        bankName: dto.bankName,
        bankBranch: dto.bankBranch,
        drawer: dto.drawer,
        amount: dto.amount,
        currency: dto.currency ?? 'TRY',
        issueDate: new Date(dto.issueDate),
        dueDate: new Date(dto.dueDate),
        status: 'PORTFOLIO',
        statusDate: new Date(),
        description: dto.description,
        createdBy: userId,
        updatedBy: userId,
      },
      include: {
        contact: { select: { id: true, code: true, name: true } },
      },
    });

    this.logger.log(
      `📋 Yeni ${cheque.kind === 'CHEQUE' ? 'çek' : 'senet'}: ${cheque.chequeNo} | ${cheque.direction} | ${cheque.amount}`,
    );

    return cheque;
  }

  // ════════════════════════════════════
  // FIND ALL
  // ════════════════════════════════════
  async findAll(tenantId: string, query: ListChequesDto) {
    const page = query.page ?? 1;
    const limit = query.limit ?? 50;
    const skip = (page - 1) * limit;

    const where: Prisma.ChequeWhereInput = {
      tenantId,
      deletedAt: null,
    };

    if (query.contactId) where.contactId = query.contactId;
    if (query.kind) where.kind = query.kind;
    if (query.direction) where.direction = query.direction;
    if (query.status) where.status = query.status;

    if (query.dueFrom || query.dueTo) {
      where.dueDate = {};
      if (query.dueFrom) where.dueDate.gte = new Date(query.dueFrom);
      if (query.dueTo) where.dueDate.lte = new Date(query.dueTo);
    }

    const [items, total] = await Promise.all([
      this.prisma.cheque.findMany({
        where,
        skip,
        take: limit,
        orderBy: { dueDate: 'asc' },
        include: {
          contact: { select: { id: true, code: true, name: true } },
          subcontractor: { select: { id: true, code: true, name: true } },
        },
      }),
      this.prisma.cheque.count({ where }),
    ]);

    return {
      items,
      pagination: { page, limit, total, totalPages: Math.ceil(total / limit) },
    };
  }

  // ════════════════════════════════════
  // FIND ONE
  // ════════════════════════════════════
  async findOne(tenantId: string, id: string) {
    const cheque = await this.prisma.cheque.findFirst({
      where: { id, tenantId, deletedAt: null },
      include: {
        contact: { select: { id: true, code: true, name: true } },
        subcontractor: { select: { id: true, code: true, name: true } },
      },
    });

    if (!cheque) {
      throw new NotFoundException(`Çek/Senet bulunamadı: ${id}`);
    }

    return cheque;
  }

  // ════════════════════════════════════
  // UPDATE STATUS
  // ════════════════════════════════════
  async updateStatus(
    tenantId: string,
    userId: string,
    id: string,
    dto: UpdateChequeStatusDto,
  ) {
    const cheque = await this.findOne(tenantId, id);

    const updated = await this.prisma.cheque.update({
      where: { id },
      data: {
        status: dto.status,
        statusDate: new Date(),
        statusNote: dto.statusNote,
        updatedBy: userId,
      },
      include: {
        contact: { select: { id: true, code: true, name: true } },
        subcontractor: { select: { id: true, code: true, name: true } },
      },
    });

    this.logger.log(
      `🔄 ${cheque.chequeNo}: ${cheque.status} → ${dto.status}`,
    );

    return updated;
  }

  // ════════════════════════════════════
  // DELETE (soft)
  // ════════════════════════════════════
  async remove(tenantId: string, userId: string, id: string) {
    const existing = await this.findOne(tenantId, id);

    if (existing.isAutoGenerated) {
      throw new BadRequestException(
        `Bu çek otomatik üretildi (${existing.sourceType}). Manuel silinemez. Kaynak kaydı (hakediş/cari hareketi/gider/fatura) iptal edilirse otomatik silinir.`,
      );
    }

    await this.prisma.cheque.update({
      where: { id },
      data: {
        deletedAt: new Date(),
        updatedBy: userId,
      },
    });

    return { message: 'Çek/Senet silindi', id };
  }

  // ════════════════════════════════════
  // DASHBOARD STATS
  // ════════════════════════════════════
  async getStats(tenantId: string) {
    const baseWhere = { tenantId, deletedAt: null };
    const today = new Date();
    today.setHours(0, 0, 0, 0);

    const thirtyDaysLater = new Date(today);
    thirtyDaysLater.setDate(thirtyDaysLater.getDate() + 30);

    const portfolioStatus: Prisma.EnumChequeStatusFilter['in'] = [
      'PORTFOLIO',
      'DEPOSITED',
      'ENDORSED',
    ];

    const [
      totalIncoming,
      totalOutgoing,
      portfolioIncoming,
      portfolioOutgoing,
      overdueIncoming,
      overdueOutgoing,
      upcomingIncoming,
      upcomingOutgoing,
      monthlyDistribution,
    ] = await Promise.all([
      this.prisma.cheque.count({
        where: { ...baseWhere, direction: 'INCOMING' },
      }),
      this.prisma.cheque.count({
        where: { ...baseWhere, direction: 'OUTGOING' },
      }),
      this.prisma.cheque.aggregate({
        where: { ...baseWhere, direction: 'INCOMING', status: { in: portfolioStatus } },
        _sum: { amount: true },
        _count: true,
      }),
      this.prisma.cheque.aggregate({
        where: { ...baseWhere, direction: 'OUTGOING', status: { in: portfolioStatus } },
        _sum: { amount: true },
        _count: true,
      }),
      this.prisma.cheque.aggregate({
        where: {
          ...baseWhere,
          direction: 'INCOMING',
          status: { in: portfolioStatus },
          dueDate: { lt: today },
        },
        _sum: { amount: true },
        _count: true,
      }),
      this.prisma.cheque.aggregate({
        where: {
          ...baseWhere,
          direction: 'OUTGOING',
          status: { in: portfolioStatus },
          dueDate: { lt: today },
        },
        _sum: { amount: true },
        _count: true,
      }),
      this.prisma.cheque.aggregate({
        where: {
          ...baseWhere,
          direction: 'INCOMING',
          status: { in: portfolioStatus },
          dueDate: { gte: today, lte: thirtyDaysLater },
        },
        _sum: { amount: true },
        _count: true,
      }),
      this.prisma.cheque.aggregate({
        where: {
          ...baseWhere,
          direction: 'OUTGOING',
          status: { in: portfolioStatus },
          dueDate: { gte: today, lte: thirtyDaysLater },
        },
        _sum: { amount: true },
        _count: true,
      }),
      this.prisma.cheque.findMany({
        where: {
          ...baseWhere,
          status: { in: portfolioStatus },
          dueDate: {
            gte: today,
            lte: new Date(today.getTime() + 180 * 24 * 60 * 60 * 1000),
          },
        },
        select: { dueDate: true, amount: true, direction: true },
        orderBy: { dueDate: 'asc' },
      }),
    ]);

    const byMonth: Record<string, { incoming: number; outgoing: number; count: number }> = {};
    for (const c of monthlyDistribution) {
      const monthKey = `${c.dueDate.getFullYear()}-${String(c.dueDate.getMonth() + 1).padStart(2, '0')}`;
      if (!byMonth[monthKey]) {
        byMonth[monthKey] = { incoming: 0, outgoing: 0, count: 0 };
      }
      const amount = parseFloat(c.amount.toString());
      if (c.direction === 'INCOMING') {
        byMonth[monthKey].incoming += amount;
      } else {
        byMonth[monthKey].outgoing += amount;
      }
      byMonth[monthKey].count += 1;
    }

    const monthlyArray = Object.entries(byMonth)
      .map(([month, data]) => ({
        month,
        incoming: data.incoming.toFixed(2),
        outgoing: data.outgoing.toFixed(2),
        count: data.count,
      }))
      .sort((a, b) => a.month.localeCompare(b.month));

    return {
      counts: { totalIncoming, totalOutgoing },
      portfolio: {
        incoming: {
          count: portfolioIncoming._count,
          total: portfolioIncoming._sum?.amount?.toString() ?? '0',
        },
        outgoing: {
          count: portfolioOutgoing._count,
          total: portfolioOutgoing._sum?.amount?.toString() ?? '0',
        },
      },
      overdue: {
        incoming: {
          count: overdueIncoming._count,
          total: overdueIncoming._sum?.amount?.toString() ?? '0',
        },
        outgoing: {
          count: overdueOutgoing._count,
          total: overdueOutgoing._sum?.amount?.toString() ?? '0',
        },
      },
      upcoming30Days: {
        incoming: {
          count: upcomingIncoming._count,
          total: upcomingIncoming._sum?.amount?.toString() ?? '0',
        },
        outgoing: {
          count: upcomingOutgoing._count,
          total: upcomingOutgoing._sum?.amount?.toString() ?? '0',
        },
      },
      monthlyDistribution: monthlyArray,
    };
  }

  // ════════════════════════════════════════════════════════════════════
  // ⚙️  OTOMATİK HELPER METOTLAR
  // ════════════════════════════════════════════════════════════════════

  /**
   * Belirli bir kaynak + çek numarası kombinasyonu zaten var mı?
   *
   * NOT: Artık chequeNo da kontrole dahil. Bir faturadan birden fazla
   * çek kesilebilir (taksitli ödeme), her biri farklı numara taşır.
   * Unique constraint: [tenantId, sourceType, sourceId, chequeNo]
   */
  private async existsFromSource(
    tenantId: string,
    sourceType: string,
    sourceId: string,
    chequeNo: string,
  ): Promise<boolean> {
    const existing = await this.prisma.cheque.findFirst({
      where: {
        tenantId,
        sourceType: sourceType as any,
        sourceId,
        chequeNo,
        deletedAt: null,
      },
      select: { id: true },
    });
    return existing !== null;
  }

  /**
   * Bir kaynaktan üretilmiş çek sayısı (otomatik numara üretimi için)
   */
  private async countFromSource(
    tenantId: string,
    sourceType: string,
    sourceId: string,
  ): Promise<number> {
    return this.prisma.cheque.count({
      where: {
        tenantId,
        sourceType: sourceType as any,
        sourceId,
        deletedAt: null,
      },
    });
  }

  // ════════════════════════════════════
  // HAKEDİŞ → ÇEK
  // ════════════════════════════════════
  async createFromProgressPayment(
    tenantId: string,
    paymentId: string,
    chequeInfo?: {
      chequeNo?: string;
      bankName?: string;
      dueDate?: string;
    },
  ) {
    try {
      const payment = await this.prisma.progressPayment.findFirst({
        where: { id: paymentId, tenantId, deletedAt: null },
        include: {
          subcontractor: { select: { id: true, name: true } },
          project: { select: { id: true, code: true, name: true } },
        },
      });

      if (!payment) {
        this.logger.warn(`⚠️  ProgressPayment bulunamadı: ${paymentId}`);
        return null;
      }

      if (payment.status !== 'PAID') {
        this.logger.warn(`⚠️  ProgressPayment PAID değil (status=${payment.status}), atlanıyor: ${payment.code}`);
        return null;
      }

      if (payment.paymentMethod !== 'CHEQUE') {
        return null;
      }

      const chequeNo = chequeInfo?.chequeNo?.trim() || `OTO-${payment.code}`;

      if (await this.existsFromSource(tenantId, 'PROGRESS_PAYMENT', paymentId, chequeNo)) {
        this.logger.log(`ℹ️  Bu hakediş için '${chequeNo}' numaralı çek zaten var, atlanıyor: ${payment.code}`);
        return null;
      }

      const bankName = chequeInfo?.bankName?.trim() || null;

      const dueDate = chequeInfo?.dueDate
        ? new Date(chequeInfo.dueDate)
        : new Date((payment.paidAt ?? new Date()).getTime() + 30 * 24 * 60 * 60 * 1000);

      const issueDate = payment.paidAt ?? new Date();

      const description = `Hakediş ödemesi - ${payment.subcontractor?.name ?? 'Bilinmiyor'} - ${payment.project?.name ?? 'Bilinmiyor'} (${payment.code})`;

      const cheque = await this.prisma.cheque.create({
        data: {
          tenantId,
          contactId: null,
          subcontractorId: payment.subcontractorId,
          kind: 'CHEQUE',
          direction: 'OUTGOING',
          chequeNo,
          bankName,
          amount: payment.totalAmount,
          currency: payment.currency,
          issueDate,
          dueDate,
          status: 'PORTFOLIO',
          statusDate: new Date(),
          description,
          sourceType: 'PROGRESS_PAYMENT',
          sourceId: paymentId,
          isAutoGenerated: true,
          createdBy: 'SYSTEM',
          updatedBy: 'SYSTEM',
        },
      });

      this.logger.log(
        `🤖 OTO Çek üretildi (Hakediş): ${cheque.chequeNo} ← ${payment.code} | vade: ${dueDate.toLocaleDateString('tr-TR')} | ${payment.totalAmount.toString()} ${payment.currency}`,
      );

      return cheque;
    } catch (error) {
      this.logger.error(`❌ createFromProgressPayment hatası: ${error instanceof Error ? error.message : String(error)}`);
      return null;
    }
  }

  // ════════════════════════════════════
  // CARİ HAREKETİ → ÇEK
  // ════════════════════════════════════
  async createFromContactTransaction(
    tenantId: string,
    transactionId: string,
    chequeInfo?: {
      chequeNo?: string;
      bankName?: string;
      dueDate?: string;
    },
  ) {
    try {
      const tx = await this.prisma.contactTransaction.findFirst({
        where: { id: transactionId, tenantId, deletedAt: null },
        include: {
          contact: { select: { id: true, code: true, name: true } },
        },
      });

      if (!tx) {
        this.logger.warn(`⚠️  ContactTransaction bulunamadı: ${transactionId}`);
        return null;
      }

      if (tx.type !== 'PAYMENT' && tx.type !== 'COLLECTION') {
        return null;
      }

      if (tx.paymentMethod !== 'CHEQUE') {
        return null;
      }

      const chequeNo = chequeInfo?.chequeNo?.trim() || `OTO-CR-${transactionId.substring(0, 8)}`;

      if (await this.existsFromSource(tenantId, 'CONTACT_TRANSACTION', transactionId, chequeNo)) {
        this.logger.log(`ℹ️  Bu cari hareketi için '${chequeNo}' numaralı çek zaten var, atlanıyor: ${transactionId}`);
        return null;
      }

      const direction: 'OUTGOING' | 'INCOMING' = tx.type === 'PAYMENT' ? 'OUTGOING' : 'INCOMING';

      const bankName = chequeInfo?.bankName?.trim() || null;

      const dueDate = chequeInfo?.dueDate
        ? new Date(chequeInfo.dueDate)
        : new Date(tx.date.getTime() + 30 * 24 * 60 * 60 * 1000);

      const issueDate = tx.date;

      const directionLabel = direction === 'OUTGOING' ? 'Ödeme' : 'Tahsilat';
      const description = `Cari ${directionLabel} - ${tx.contact?.name ?? 'Bilinmiyor'}${tx.description ? ` (${tx.description})` : ''}`;

      const cheque = await this.prisma.cheque.create({
        data: {
          tenantId,
          contactId: tx.contactId,
          subcontractorId: null,
          kind: 'CHEQUE',
          direction,
          chequeNo,
          bankName,
          amount: tx.amount,
          currency: tx.currency,
          issueDate,
          dueDate,
          status: 'PORTFOLIO',
          statusDate: new Date(),
          description,
          sourceType: 'CONTACT_TRANSACTION',
          sourceId: transactionId,
          isAutoGenerated: true,
          createdBy: 'SYSTEM',
          updatedBy: 'SYSTEM',
        },
      });

      this.logger.log(
        `🤖 OTO Çek üretildi (Cari ${tx.type}): ${cheque.chequeNo} | ${direction} | ${tx.contact?.name} | vade: ${dueDate.toLocaleDateString('tr-TR')} | ${tx.amount.toString()} ${tx.currency}`,
      );

      return cheque;
    } catch (error) {
      this.logger.error(`❌ createFromContactTransaction hatası: ${error instanceof Error ? error.message : String(error)}`);
      return null;
    }
  }

  // ════════════════════════════════════
  // MANUEL GİDER → ÇEK
  // ════════════════════════════════════
  async createFromExpense(
    tenantId: string,
    expenseId: string,
    chequeInfo?: {
      chequeNo?: string;
      bankName?: string;
      dueDate?: string;
    },
  ) {
    try {
      const expense = await this.prisma.expense.findFirst({
        where: { id: expenseId, tenantId, deletedAt: null },
        include: {
          contact: { select: { id: true, code: true, name: true } },
          subcontractor: { select: { id: true, code: true, name: true } },
        },
      });

      if (!expense) {
        this.logger.warn(`⚠️  Expense bulunamadı: ${expenseId}`);
        return null;
      }

      // Otomatik üretilen expense'ler için çek üretme (çift sayım engeli)
      if (expense.isAutoGenerated) {
        this.logger.log(`ℹ️  Expense otomatik üretildi, çek üretilmeyecek: ${expense.code}`);
        return null;
      }

      // Sadece CHEQUE paymentMethod için
      if (expense.paymentMethod !== 'CHEQUE') {
        return null;
      }

      const chequeNo = chequeInfo?.chequeNo?.trim() || `OTO-${expense.code}`;

      if (await this.existsFromSource(tenantId, 'EXPENSE', expenseId, chequeNo)) {
        this.logger.log(`ℹ️  Bu gider için '${chequeNo}' numaralı çek zaten var, atlanıyor: ${expense.code}`);
        return null;
      }

      const bankName = chequeInfo?.bankName?.trim() || null;

      // Vade: kullanıcı verdiyse onu, yoksa gider tarihinden 30 gün sonrası
      const dueDate = chequeInfo?.dueDate
        ? new Date(chequeInfo.dueDate)
        : new Date(expense.date.getTime() + 30 * 24 * 60 * 60 * 1000);

      const issueDate = expense.paidAt ?? expense.date;

      // Alıcı: hangi varsa onu kullan (contact > subcontractor > sadece description)
      const recipientName =
        expense.contact?.name ?? expense.subcontractor?.name ?? 'Bilinmiyor';

      const description = `Gider ödemesi - ${recipientName} (${expense.code}: ${expense.description})`;

      const cheque = await this.prisma.cheque.create({
        data: {
          tenantId,
          contactId: expense.contactId,
          subcontractorId: expense.subcontractorId,
          kind: 'CHEQUE',
          direction: 'OUTGOING', // Gider = biz ödedik = çek verdik
          chequeNo,
          bankName,
          amount: expense.totalAmount,
          currency: expense.currency,
          issueDate,
          dueDate,
          status: 'PORTFOLIO',
          statusDate: new Date(),
          description,
          sourceType: 'EXPENSE',
          sourceId: expenseId,
          isAutoGenerated: true,
          createdBy: 'SYSTEM',
          updatedBy: 'SYSTEM',
        },
      });

      this.logger.log(
        `🤖 OTO Çek üretildi (Gider): ${cheque.chequeNo} ← ${expense.code} | ${recipientName} | vade: ${dueDate.toLocaleDateString('tr-TR')} | ${expense.totalAmount.toString()} ${expense.currency}`,
      );

      return cheque;
    } catch (error) {
      this.logger.error(`❌ createFromExpense hatası: ${error instanceof Error ? error.message : String(error)}`);
      return null;
    }
  }

  // ════════════════════════════════════
  // FATURA → ÇEK (YENİ)
  // ════════════════════════════════════
  // Bir faturadan BİRDEN FAZLA çek kesilebilir (taksitli ödeme).
  // chequeNo verilmezse OTO-{code}-1, -2, -3... şeklinde artan üretilir.
  //
  // direction:
  //   PURCHASE (alış) → OUTGOING (biz tedarikçiye çek verdik)
  //   SALES (satış)   → INCOMING (müşteriden çek aldık)
  // ════════════════════════════════════
  async createFromInvoice(
    tenantId: string,
    invoiceId: string,
    chequeInfo?: {
      chequeNo?: string;
      bankName?: string;
      dueDate?: string;
      amount?: number | string; // taksit tutarı; verilmezse fatura toplamı
    },
  ) {
    try {
      const invoice = await this.prisma.invoice.findFirst({
        where: { id: invoiceId, tenantId, deletedAt: null },
      });

      if (!invoice) {
        this.logger.warn(`⚠️  Invoice bulunamadı: ${invoiceId}`);
        return null;
      }

      if (invoice.paymentMethod !== 'CHEQUE') {
        return null;
      }

      // Çek numarası: verilmezse sıra numaralı otomatik üret
      let chequeNo = chequeInfo?.chequeNo?.trim();
      if (!chequeNo) {
        const existingCount = await this.countFromSource(tenantId, 'INVOICE', invoiceId);
        chequeNo = `OTO-${invoice.code}-${existingCount + 1}`;
      }

      if (await this.existsFromSource(tenantId, 'INVOICE', invoiceId, chequeNo)) {
        this.logger.log(`ℹ️  Bu fatura için '${chequeNo}' numaralı çek zaten var, atlanıyor: ${invoice.code}`);
        return null;
      }

      // Cari bilgisi (açıklama için)
      const contact = await this.prisma.contact.findFirst({
        where: { id: invoice.contactId, tenantId },
        select: { name: true },
      });

      const direction: 'OUTGOING' | 'INCOMING' =
        invoice.type === 'PURCHASE' ? 'OUTGOING' : 'INCOMING';

      const bankName = chequeInfo?.bankName?.trim() || null;

      const amount = chequeInfo?.amount
        ? new Prisma.Decimal(chequeInfo.amount)
        : invoice.totalAmount;

      const dueDate = chequeInfo?.dueDate
        ? new Date(chequeInfo.dueDate)
        : (invoice.dueDate ??
          new Date(invoice.invoiceDate.getTime() + 30 * 24 * 60 * 60 * 1000));

      const typeLabel = invoice.type === 'PURCHASE' ? 'Alış' : 'Satış';
      const description = `${typeLabel} faturası - ${contact?.name ?? 'Bilinmiyor'} (${invoice.code})`;

      const cheque = await this.prisma.cheque.create({
        data: {
          tenantId,
          contactId: invoice.contactId,
          subcontractorId: null,
          invoiceId,
          kind: 'CHEQUE',
          direction,
          chequeNo,
          bankName,
          amount,
          currency: invoice.currency,
          issueDate: invoice.invoiceDate,
          dueDate,
          status: 'PORTFOLIO',
          statusDate: new Date(),
          description,
          sourceType: 'INVOICE',
          sourceId: invoiceId,
          isAutoGenerated: true,
          createdBy: 'SYSTEM',
          updatedBy: 'SYSTEM',
        },
      });

      this.logger.log(
        `🤖 OTO Çek üretildi (Fatura): ${cheque.chequeNo} ← ${invoice.code} | ${direction} | ${contact?.name} | vade: ${dueDate.toLocaleDateString('tr-TR')} | ${amount.toString()} ${invoice.currency}`,
      );

      return cheque;
    } catch (error) {
      this.logger.error(`❌ createFromInvoice hatası: ${error instanceof Error ? error.message : String(error)}`);
      return null;
    }
  }

  // ════════════════════════════════════
  // GERİ ÇEKME
  // ════════════════════════════════════
  // NOT: Bir kaynaktan birden fazla çek olabileceği için artık
  // findMany kullanılıyor — hepsi geri çekilir.
  // ════════════════════════════════════
  async deleteBySource(
    tenantId: string,
    sourceType: 'PROGRESS_PAYMENT' | 'CONTACT_TRANSACTION' | 'EXPENSE' | 'INVOICE',
    sourceId: string,
  ) {
    try {
      const cheques = await this.prisma.cheque.findMany({
        where: {
          tenantId,
          sourceType,
          sourceId,
          deletedAt: null,
        },
      });

      if (cheques.length === 0) {
        return null;
      }

      const deleted: string[] = [];
      const skipped: string[] = [];

      for (const cheque of cheques) {
        // Tahsil sürecine girmiş çekler geri çekilmez
        if (['COLLECTED', 'PAID', 'DEPOSITED'].includes(cheque.status)) {
          this.logger.warn(
            `⚠️  Otomatik çek silinmedi (status=${cheque.status}, çek tahsil sürecinde): ${cheque.chequeNo}`,
          );
          skipped.push(cheque.chequeNo);
          continue;
        }

        await this.prisma.cheque.update({
          where: { id: cheque.id },
          data: {
            deletedAt: new Date(),
            updatedBy: 'SYSTEM',
          },
        });

        deleted.push(cheque.chequeNo);
      }

      if (deleted.length > 0) {
        this.logger.log(
          `🔄 OTO Çek geri çekildi (${deleted.length} adet): ${deleted.join(', ')} (kaynak ${sourceType} ${sourceId})`,
        );
      }

      return { deleted, skipped };
    } catch (error) {
      this.logger.error(`❌ deleteBySource hatası: ${error instanceof Error ? error.message : String(error)}`);
      return null;
    }
  }
}